### ISSUE TITLE
发送“代刀”、“代刀中”、“开始代刀”指令没有回应

### ISSUE THREAD

**Issue by MakiseKumarisu** [sdyxxjj123/Daidao#5]
平台：linux centos 7
gocq版本：1.0.0beta4
yobot版本：3.6.11 源码版

开启了主动私聊，手动设置了yobotdata.db和yobot主页的地址，使用时发送其他指令均有回复，只有“代刀中”指令没有任何回应。

log中未见异常

**Comment by sdyxxjj123** [comment]
请检查代刀插件版本，在某一中间版本时曾有该问题

**Comment by MakiseKumarisu** [comment]
已确认插件版本为v0.7
问题依然存在

补充：每次启动hoshinobot加载插件时会提示
`ERROR: 【代刀插件】网络错误`

**Comment by MakiseKumarisu** [comment]
已确认插件版本为v0.7
问题依然存在

补充：每次启动hoshinobot加载插件时会提示
`ERROR: 【代刀插件】网络错误`

**Comment by sdyxxjj123** [comment]
网络错误是因为我只有在发新版本那几天才会开启服务器，请确认您的数据库地址正确且至少有一刀数据，并仔细确认日志是否有误，是否有其他插件命令冲突。
如仍无法解决问题，也可以加我QQ944542670联系

**Comment by MakiseKumarisu** [comment]
问题已解决，数据库路径不正确，/root不能用~代替，谢谢解答
