### ISSUE TITLE
yobot指令冲突

### ISSUE THREAD

**Issue by Inend** [sdyxxjj123/Daidao#8]
所有和yobot相同的命令都不生效，但改用英文可以生效
例如：@sv.on_rex(r'^尾$')
改成尾生效 原本的尾刀不生效

似乎是rex后面汉字长度如果大于1，则无法生效，与冲突与否无关

**Comment by sdyxxjj123** [comment]
建议检查您的设置，也可以贴上日志供我检查，若所有和yobot相同的命令都不生效，那么这个插件从最初的版本就不成立。

**Comment by sdyxxjj123** [comment]
问题已解决，若同样有遇到该问题的，请更新Hoshino本体
